config/routes.rb
SignificantWeb::Application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users
      resources :races
      resources :runs
    end
  end

  resources :races, only: [:index, :show]
  resources :users, only: [:index]

  root to: 'races#index'
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :race
  attr_accessible :milestone, :name

  default_scope order(:milestone)

  def progress
    (accumulated >= milestone) ? 1.0 : (accumulated.to_f / milestone.to_f)
  end

  def accumulated
    race.runs.sum(:score)
  end

  def completed?
    accumulated >= milestone
  end

  def created_at_int
    created_at.to_i * 1000
  end

  def updated_at_int
    updated_at.to_i * 1000
  end
end

app/models/race.rb
class Race < ActiveRecord::Base
  attr_accessible :long_description, :name, :short_description, :logo, :youtube_id

  has_attached_file :logo
  has_attached_file :institution_image

  has_many :goals
  has_many :runs
  has_many :race_run_types
  has_many :run_types, through: :race_run_types
  has_many :sponsors


  def progress
    accumulated / last_milestone
  end

  def accumulated
    runs.sum(:score)
  end

  def created_at_int
    created_at.to_i * 1000
  end

  def updated_at_int
    updated_at.to_i * 1000
  end

  def last_milestone
    goals.last.milestone
  end

  def current_goal
    _goal = nil
    goals.order(:milestone).each do |goal|
      if not goal.completed?
        _goal = goal
        break
      end
    end
    if not _goal.nil?
      _goal
    else
      _goal = goals.last
    end
    _goal
  end

end

app/models/race_run_type.rb
class RaceRunType < ActiveRecord::Base
  belongs_to :race
  belongs_to :run_type
  # attr_accessible :title, :body
end

app/models/run.rb
# encoding: utf-8
class Run < ActiveRecord::Base
  belongs_to :run_type
  belongs_to :race
  belongs_to :user
  attr_accessible :average_speed, :ended_at, :started_at, :total_distance, :total_time, :run_type_id, :user_id, :race_id, :share_message

  validates :average_speed, :started_at, :ended_at, :total_distance, :total_time, :run_type_id, :user_id, :race_id, presence: true

  scope :by_type, lambda { |run_type_id| where(run_type_id: run_type_id)}

  before_save :set_score, :set_share_message
  before_validation :set_average_speed

  def started_at_int
    started_at.to_i * 1000
  end

  def ended_at_int
    ended_at.to_i * 1000
  end

  def created_at_int
    created_at.to_i * 1000
  end

  def updated_at_int
    updated_at.to_i * 1000
  end

  def set_score
    self.score = self.total_distance * self.run_type.modifier
  end

  def set_average_speed
    self.average_speed = ((self.total_distance.to_f/(self.total_time.to_f / 1000.0)) * 3.6).round(2)
  end

  def average_speed_text
    "#{average_speed.round(2)} Km/h"
  end

  def score_int
    self.score.to_i
  end

  def to_km
    (total_distance / 1000.to_f).round(2)
  end

  def set_share_message
    self.share_message = "Acabo de aportar #{to_km} Km de #{run_type.name}, para la campaña #{race.name}"
  end

end

app/models/run_type.rb
class RunType < ActiveRecord::Base
  attr_accessible :name

  validates :name, :modifier, presence: true
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  belongs_to :race
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :birthday, :email, :name, :oauth_token, :uid, :oauth_expires_at

  has_many :runs

  validates :name, :email, :uid, presence: true

  validates :email, uniqueness: true


  def self.find_by_id_or_facebook_id _id
    _user = find_by_id(_id) || find_by_uid(_id)
    if _user
      _user
    else
      raise ActiveRecord::RecordNotFound
    end
  end

  def created_at_int
    created_at.to_i * 1000
  end

  def updated_at_int
    updated_at.to_i * 1000
  end

  def birthday_int
    birthday.to_datetime.to_i * 1000 if birthday
  end

  def oauth_expires_at_int
    oauth_expires_at.to_i * 1000
  end

end

app/controllers/api/v1/races_controller.rb
class Api::V1::RacesController < ApplicationController
  respond_to :json

  def index
    @races = Race.all
    respond_with @races
  end

  def show
    @race = Race.find params[:id]
    respond_with @race
  end

  def create
    @race = Race.new params[:race]
    if @race.save
      respond_with @race, status: :created, location: api_v1_race_path(@race)
    else
      respond_with @race
    end
  end

  def update
    
  end

  def destroy
    
  end

end

app/controllers/api/v1/runs_controller.rb
class Api::V1::RunsController < ApplicationController
  respond_to :json

  before_filter :utc_to_datetime, only: [:create]

  def show
    @run = Run.find params[:id]
    respond_with @run
  end

  def create
    @run = Run.new params[:run]
    if @run.save
      respond_with @run, status: :created, location: api_v1_run_path(@run)
    else
      respond_with @run
    end
  end

  private

  def utc_to_datetime
    params[:run][:started_at] = Time.at(params[:run][:started_at] / 1000)
    params[:run][:ended_at] = Time.at(params[:run][:ended_at] / 1000)
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  respond_to :json

  before_filter :utc_to_datetime, only: [:create]

  def show
    @user = User.find_by_id_or_facebook_id params[:id]
    respond_with @user, status: :ok
  end

  def create
    @user = User.new params[:user]

    if @user.save
      respond_with @user, status: :created, location: api_v1_user_path(@user)
    else
      respond_with @user
    end
  end

  def update
    
  end

  def destroy
    
  end

  private

  def utc_to_datetime
    params[:user][:oauth_expires_at] = Time.at(params[:user][:oauth_expires_at]/1000)
    params[:user][:birthday] = Time.at(params[:user][:birthday]/1000).to_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "significant" && password == "diablo666"
    end
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_filter :authenticate

  def index
    @races = Race.all
  end

  def show
    @race = Race.find params[:id]
    @runs = @race.runs.includes(:user).order('created_at desc')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate

  def index
    @users = User.order(:name)
    @user_count = @users.size
  end
end

app/helpers/api/v1/races_helper.rb
module Api::V1::RacesHelper
end

app/helpers/api/v1/runs_helper.rb
module Api::V1::RunsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Significant" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Significant</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Campañas", races_path  %></li>
              <li><%= link_to "Usuarios", users_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/races/index.html.erb
<h1>Listado de Campañas</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Progreso</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.name %></td>
        <td>
          <div class="progress">
            <div class="bar" style="width: <%= number_to_percentage race.progress*100, precision: 0 %>;"></div>
          </div>
        </td>
        <td>
          <%= link_to 'Detalle', race_path(race), class: 'btn btn-info' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/races/show.html.erb
<h1><%= @race.name %></h1>

<p><%= @race.long_description.html_safe %></p>


<h2>Actividad</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Nombre</th>
      <th>Email</th>
      <th>Distancia</th>
      <th>Fecha</th>
    </tr>
  </thead>

  <tbody>
    <% @runs.each do |run| %>
      <tr>
        <td><%= run.run_type.name %></td>
        <td><%= run.user.name %></td>
        <td><%= run.user.email %></td>
        <td><%= run.to_km %> Km</td>
        <td><%= l run.created_at, format: :short %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<h1>Usuarios <small><%= @user_count %></small></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Fecha Registro</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= l user.created_at, format: :short %></td>
      </tr>
    <% end %>
  </tbody>
</table>